# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0431a7007ea2c17dec83637af8fb5046bb773136024bd67386abbed6a73ff67404f867b2c5dc3cbf4a3c40bd997c6f3e064f0172264c3782cd7eac68055a267c

test:
  secret_key_base: f7054ae7042ddb19d0e4bd5c10cec042b7bf9b428250b57db63852982560861c04d69cd4ef1ba8ef5c91b9c2b16cc714289680de8e78d2eb049de5b132bde3fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
